#!/bin/bash
# $IMAGE_NAME var is injected into the build so the tag is correct.
if [ "${SOURCE_BRANCH}" != "master" ]; then export BUILD_TAG=${SOURCE_BRANCH}; else export BUILD_TAG=latest; fi
docker build --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
  --build-arg LOGSPOUT_VERSION=${BUILD_TAG} \
  -t $IMAGE_NAME .
